In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files
upload=files.upload()

Saving olist_customers_dataset.csv to olist_customers_dataset.csv
Saving olist_order_items_dataset.csv to olist_order_items_dataset.csv
Saving olist_order_payments_dataset.csv to olist_order_payments_dataset.csv
Saving olist_orders_dataset.csv to olist_orders_dataset.csv
Saving olist_products_dataset.csv to olist_products_dataset.csv

In [ ]:
orders=pd.read_csv('olist_orders_dataset.csv')
customers=pd.read_csv("olist_customers_dataset.csv")
products=pd.read_csv("olist_products_dataset.csv")
order_items=pd.read_csv("olist_order_items_dataset.csv")
order_payments=pd.read_csv("olist_order_payments_dataset.csv")

In [ ]:
print("orders shape:",orders.shape),
print("customers",customers.shape),
print("products",products.shape),
print("order_items",order_items.shape),
print("order_payments",order_payments.shape)

orders shape: (99441, 8)
customers (99441, 5)
products (32951, 9)
order_items (112650, 7)
order_payments (103886, 5)

In [ ]:
print(orders.columns),
print(order_items.columns),
print(order_payments.columns),
print(products.columns),
print(customers.columns)

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='object')
Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='object')
Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='object')
Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='object')
Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='object')

In [ ]:
print(orders.head(5))

                           order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c

  order_status order_purchase_timestamp    order_approved_at  \
0    delivered      2017-10-02 10:56:33  2017-10-02 11:07:15
1    delivered      2018-07-24 20:41:37  2018-07-26 03:24:27
2    delivered      2018-08-08 08:38:49  2018-08-08 08:55:23
3    delivered      2017-11-18 19:28:06  2017-11-18 19:45:59
4    delivered      2018-02-13 21:18:39  2018-02-13 22:20:29

  order_delivered_carrier_date order_delivered_customer_date  \
0          2017-10-04 19:55:00           2017-10-10 21:25:13
1          2018-07-26 14:31:00           2018-08-07 15:27:45
2          2018-08-08 13:50:00           2018-08-17 18:06:29
3          2017-11-22 13:39:59           2017-12-02 00:28:42
4          2018-02-14 19:46:34           2018-02-16 18:17:02

  order_estimated_delivery_date
0           2017-10-18 00:00:00
1           2018-08-13 00:00:00
2           2018-09-04 00:00:00
3           2017-12-15 00:00:00
4           2018-02-26 00:00:00

In [ ]:
def audit_framework(df):
  report=pd.DataFrame({
      "columns":df.columns,
      "datatypes":df.dtypes,
      "missing_values":df.isnull().sum(),
      "missing_percentage":(df.isnull().sum()/len(df))*100,
      "unique_vlaues":df.nunique()
  })
  return report.sort_values("missing_percentage",ascending=False)
audit_framework(orders)

,columns,datatypes,missing_values,missing_percentage,unique_vlaues
order_delivered_customer_date,order_delivered_customer_date,object,2965,2.981668,95664
order_delivered_carrier_date,order_delivered_carrier_date,object,1783,1.793023,81018
order_approved_at,order_approved_at,object,160,0.160899,90733
order_id,order_id,object,0,0.000000,99441
order_purchase_timestamp,order_purchase_timestamp,object,0,0.000000,98875
order_status,order_status,object,0,0.000000,8
customer_id,customer_id,object,0,0.000000,99441
order_estimated_delivery_date,order_estimated_delivery_date,object,0,0.000000,459

In [ ]:
audit_framework(customers)

,columns,datatypes,missing_values,missing_percentage,unique_vlaues
customer_id,customer_id,object,0,0.0,99441
customer_unique_id,customer_unique_id,object,0,0.0,96096
customer_zip_code_prefix,customer_zip_code_prefix,int64,0,0.0,14994
customer_city,customer_city,object,0,0.0,4119
customer_state,customer_state,object,0,0.0,27

In [ ]:
audit_framework(products)

,columns,datatypes,missing_values,missing_percentage,unique_vlaues
product_category_name,product_category_name,object,610,1.851234,73
product_description_lenght,product_description_lenght,float64,610,1.851234,2960
product_name_lenght,product_name_lenght,float64,610,1.851234,66
product_photos_qty,product_photos_qty,float64,610,1.851234,19
product_weight_g,product_weight_g,float64,2,0.006070,2204
product_height_cm,product_height_cm,float64,2,0.006070,102
product_length_cm,product_length_cm,float64,2,0.006070,99
product_width_cm,product_width_cm,float64,2,0.006070,95
product_id,product_id,object,0,0.000000,32951

In [ ]:
audit_framework(order_items)

,columns,datatypes,missing_values,missing_percentage,unique_vlaues
order_id,order_id,object,0,0.0,98666
order_item_id,order_item_id,int64,0,0.0,21
product_id,product_id,object,0,0.0,32951
seller_id,seller_id,object,0,0.0,3095
shipping_limit_date,shipping_limit_date,object,0,0.0,93318
price,price,float64,0,0.0,5968
freight_value,freight_value,float64,0,0.0,6999

In [ ]:
audit_framework(order_payments)

,columns,datatypes,missing_values,missing_percentage,unique_vlaues
order_id,order_id,object,0,0.0,99440
payment_sequential,payment_sequential,int64,0,0.0,29
payment_type,payment_type,object,0,0.0,5
payment_installments,payment_installments,int64,0,0.0,24
payment_value,payment_value,float64,0,0.0,29077

In [ ]:
orders["order_id"].nunique(),len(orders)

(99441, 99441)

In [ ]:
order_items["order_id"].nunique(),len(order_items)

(98666, 112650)

In [ ]:
order_items["price"].describe()

count    112650.000000
mean        120.653739
std         183.633928
min           0.850000
25%          39.900000
50%          74.990000
75%         134.900000
max        6735.000000
Name: price, dtype: float64

In [ ]:
(order_items["price"] <= 0).sum()

np.int64(0)

In [ ]:
order_payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [ ]:
order_payments["payment_value"].isna().sum()

np.int64(0)

In [ ]:
(order_payments["payment_value"]<0).sum()

np.int64(0)

In [ ]:
order_payments["order_id"].isna().sum()

np.int64(0)

In [ ]:
orders_clean=orders[["order_id","customer_id","order_purchase_timestamp"]]

In [ ]:
customers_clean = customers[
    ["customer_id", "customer_state"]
]

order_items_clean = order_items[
    ["order_id", "product_id", "price"]
]

products_clean = products[
    ["product_id", "product_category_name"]
]

payments_clean = order_payments[
    ["order_id", "payment_value"]
]

In [ ]:
orders_clean.isnull().sum()
customers_clean.isnull().sum()
order_items_clean.isnull().sum()
products_clean.isnull().sum()
payments_clean.isnull().sum()

order_id         0
payment_value    0
dtype: int64

In [ ]:
import duckdb

In [ ]:
con = duckdb.connect("ecommerce.db")

In [ ]:
con.register("orders",orders_clean),
con.register("customers",customers_clean),
con.register("order_items",order_items_clean),
con.register("products",products_clean),
con.register("payments",payments_clean)

In [ ]:
con.execute("select count(*) from orders_clean").fetchall()

[(99441,)]

In [ ]:
con.execute("select count(*) from payments_clean").fetchall()

[(103886,)]

total revnue

In [ ]:
con.execute("select sum(payment_value) from  payments").fetchall()

[(16008872.119998775,)]

total orders

In [ ]:
con.execute("select count(distinct order_id)  from orders_clean").fetchall()

[(99441,)]

Which product categories generate the most revenue?

In [ ]:
con.execute("SELECT p.product_category_name,SUM(oi.price) AS total_revenue FROM order_items oi JOIN products p ON oi.product_id = p.product_id GROUP BY p.product_category_name ORDER BY total_revenue DESC limit 5").fetchall()

[('beleza_saude', 1258681.339999999),
 ('relogios_presentes', 1205005.6800000104),
 ('cama_mesa_banho', 1036988.6800000605),
 ('esporte_lazer', 988048.9700000347),
 ('informatica_acessorios', 911954.3200000328)]

Which states generate the most orders?

In [ ]:
con.execute("SELECT customers.customer_state,COUNT(order_id) as order_count FROM orders INNER JOIN customers ON orders.customer_id=customers.customer_id GROUP BY customers.customer_state ORDER BY  order_count desc limit 10 ").fetchall()

[('SP', 41746),
 ('RJ', 12852),
 ('MG', 11635),
 ('RS', 5466),
 ('PR', 5045),
 ('SC', 3637),
 ('BA', 3380),
 ('DF', 2140),
 ('ES', 2033),
 ('GO', 2020)]

average value

In [ ]:
con.execute("SELECT SUM(payment_value) / COUNT(DISTINCT order_id) AS avg_order_value FROM payments").fetchall()

[(160.9902666934712,)]

monthly sales trend

In [ ]:
con.execute("SELECT DATE_TRUNC('month',CAST(order_purchase_timestamp AS TIMESTAMP)) AS month, COUNT(order_id) AS total_orders FROM orders GROUP BY month ORDER BY month;").fetchall()

[(datetime.date(2016, 9, 1), 4),
 (datetime.date(2016, 10, 1), 324),
 (datetime.date(2016, 12, 1), 1),
 (datetime.date(2017, 1, 1), 800),
 (datetime.date(2017, 2, 1), 1780),
 (datetime.date(2017, 3, 1), 2682),
 (datetime.date(2017, 4, 1), 2404),
 (datetime.date(2017, 5, 1), 3700),
 (datetime.date(2017, 6, 1), 3245),
 (datetime.date(2017, 7, 1), 4026),
 (datetime.date(2017, 8, 1), 4331),
 (datetime.date(2017, 9, 1), 4285),
 (datetime.date(2017, 10, 1), 4631),
 (datetime.date(2017, 11, 1), 7544),
 (datetime.date(2017, 12, 1), 5673),
 (datetime.date(2018, 1, 1), 7269),
 (datetime.date(2018, 2, 1), 6728),
 (datetime.date(2018, 3, 1), 7211),
 (datetime.date(2018, 4, 1), 6939),
 (datetime.date(2018, 5, 1), 6873),
 (datetime.date(2018, 6, 1), 6167),
 (datetime.date(2018, 7, 1), 6292),
 (datetime.date(2018, 8, 1), 6512),
 (datetime.date(2018, 9, 1), 16),
 (datetime.date(2018, 10, 1), 4)]

In [ ]:
final_df=con.execute("SELECT o.order_id,CAST(o.order_purchase_timestamp AS TIMESTAMP) AS purchase_date,c.customer_state,p.product_category_name,oi.price,pay.payment_value FROM orders o JOIN customers c ON o.customer_id = c.customer_id JOIN order_items oi ON o.order_id = oi.order_id JOIN products p ON oi.product_id = p.product_id JOIN payments pay ON o.order_id = pay.order_id;").df()

In [ ]:
final_df.to_csv("e-commerce_analysis_dataset.csv",index=False)